version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    ports:
      - 8000:8000
    links:
      - db:db
    env_file:
      - .env
    volumes:
      - .:/app
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #    env_file:
    #        - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social-media
      - PGPORT=5432
      - POSTGRES_USER=postgres
    restart: on-failure
    ports:
      - "5432:5432"
volumes:
  postgres_data:
